name: ktlintCheck

on: [push]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '19'
          cache: 'gradle'
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew ktlintCheck